version: '3.0'
services:
  app:
    build:
      dockerfile: ./dockerfile/app/Dockerfile
      context: .
  rproxy:
    build:
      dockerfile: Dockerfile
      context: ./dockerfile/rproxy
    ports:
      - 8080:80