version: '3.0'
services:
  app:
    build:
      dockerfile: ./dockerfile/app/Dockerfile
      context: .
  rproxy:
    build:
      dockerfile: Dockerfile
      context: ./dockerfile/rproxy
  envoy:
    build:
      dockerfile: Dockerfile
      context: ./dockerfile/envoy
    ports:
      - 8080:8080