version: '3.0'
services:
  app:
    build:
      dockerfile: ./dockerfile/app/Dockerfile
      context: .
  rproxy:
    build:
      dockerfile: Dockerfile
      context: ./dockerfile/rproxy
    ports:
      - 8080:80
  prometheus-exporter:
    image: nginx/nginx-prometheus-exporter:0.9.0
    command: -nginx.scrape-uri=http://rproxy:80/stub_status
  prometheus:
    build:
      context: ./dockerfile/prometheus
      dockerfile: Dockerfile
  grafana:
    image: grafana/grafana:8.3.3
    ports:
      - 3000:3000