[package]
description = "A simple satysfi mathematics rendering server"
edition = "2021"
name = "satymathbot"
version = "0.1.0"

[[bin]]
name = "satymathbot"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.51"
askama = "0.10.5"
axum = "0.4.2"
base64 = "0.13.0"
clap = {version = "3.0.0-rc.7", features = ["derive"]}
futures = "0.3.19"
hyper = {version = "0.14.16", default-features = false}
hyperlocal = "0.8.0"
image = {version = "0.23.14", default-features = false, features = ["png"]}
lru = "0.7.1"
ron = "0.7.0"
serde = {version = "1.0.132", features = ["derive"]}
tokio = {version = "1.15.0", features = ["macros", "fs", "process", "io-util", "rt-multi-thread", "signal"]}
tracing = "0.1.29"
tracing-subscriber = {version = "0.3.3", default-features = false, features = ["fmt"]}
