VERSION 0.6
FROM public.ecr.aws/docker/library/rust:latest
RUN cargo install cargo-chef
WORKDIR /work
SAVE IMAEG --cache-hint

satysfi:
    FROM ocaml/opam:ubuntu-22.10-ocaml-4.10
    RUN opam repository add satysfi-external https://github.com/gfngfn/satysfi-external-repo.git
    RUN opam repository add satyrographos https://github.com/na4zagin3/satyrographos-repo.git
    RUN opam update

    USER root
    RUN apt-get update && apt-get install -y pkg-config

    USER opam
    RUN opam install -y \
        satysfi satysfi-dist satyrographos \
        satysfi-siunitx satysfi-uline satysfi-matrix
    RUN opam exec -- satyrographos install
    SAVE IMAEG --cache-hint
    SAVE ARTIFACT /home/opam/.opam/4.10/share/satysfi /share
    SAVE ARTIFACT /home/opam/.satysfi/dist /dist
    SAVE ARTIFACT /home/opam/.opam/4.10/bin/satysfi /bin

plan:
    COPY Cargo.* .
    RUN cargo chef prepare --recipe-path recipe.json
    SAVE ARTIFACT recipe.json /recipe.json

satymathbot:
    COPY +plan/recipe.json .
    RUN cargo chef cook --release --recipe-path recipe.json
    COPY src src
    COPY templates templates
    RUN cargo build --release
    RUN strip target/release/satymathbot
    SAVE IMAEG --cache-hint
    SAVE ARTIFACT target/release/satymathbot /bin

image:
    FROM public.ecr.aws/ubuntu/ubuntu:22.10
    RUN apt-get update && apt-get upgrade -y && apt-get install -y poppler-utils libjpeg-dev sudo
    COPY +satymathbot/bin /usr/local/bin/satymathbot
    COPY +satysfi/bin /usr/local/bin/satysfi
    COPY +satysfi/share /home/opam/.opam/4.10/share/satysfi
    COPY +satysfi/dist /home/satymathbot/.satysfi/dist
    COPY prod.ron /etc/satymathbot/config.ron
    COPY satysfi/empty.satyh /etc/satymathbot/empty.satyh
    COPY entry.sh /usr/local/bin/entry.sh

    RUN groupadd -g 1000 satymathbot && useradd -rm -s /bin/bash -u 1000 -g satymathbot satymathbot
    RUN chown root:root /usr/local/bin/entry.sh && chmod 4755 /usr/local/bin/entry.sh
    RUN chown satymathbot:satymathbot /usr/local/bin/satymathbot && chmod 4755 /usr/local/bin/satymathbot
    VOLUME [ "/var/run/satymathbot" ]

    ENTRYPOINT [ "/usr/local/bin/entry.sh" ]
    CMD [ "-s", "/etc/satymathbot/config.ron" ]
    SAVE IMAEG --cache-hint
