server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: http://172.16.1.240:3100/api/prom/push

scrape_configs:
  - job_name: application
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          __path__: /var/run/satymathbot/nginx.log
      - targets:
          - localhost
        labels:
          job: envoy
          __path__: /var/run/satymathbot/envoy.log
    pipeline_stages:
      - match:
          selecter: '{job="envoy"}'
          stages:
            - json:
                expressions:
                  upstream: upstream
                  id: id
                  ua: ua
                  path: path
                  method: method
                  res: res
            - labels:
                upstream:
                id:
                ua:
                path:
                method:
                res:
