VERSION 0.6
image:
	FROM public.ecr.aws/ubuntu/ubuntu:23.04

	RUN uname -m | sed -e 's/x86_64/amd64/' -e 's/aarch64/arm64/' > ~/.arch
	RUN apt-get update && apt-get install -y curl unzip
	RUN curl -L https://github.com/grafana/loki/releases/download/v2.7.1/promtail-linux-$(cat ~/.arch).zip -o /root/promtail.zip
	RUN unzip /root/promtail.zip -d /usr/local/bin
	RUN mv /usr/local/bin/promtail-linux-$(cat ~/.arch) /usr/local/bin/promtail
	COPY config.yml /etc/promtail/config.yml

	ENTRYPOINT [ "/usr/local/bin/promtail" ]
	CMD ["-config.file", "/etc/promtail/config.yml"]
