name: container build
on: [push]
jobs:
  earthly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Earthly
        uses: earthly/actions-setup@v1.0.1
        with:
          version: v0.6.20
      - name: Login to ghcr.io
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push docker image as latest
        env:
          CACHE_REGISTRY: ghcr.io/${{ github.repository_owner }}/satymathbot:cache
        run: |
          earthly --push --ci --repo=ghcr.io/namachan10777 --remote-cache="${CACHE_REGISTRY}" +images
