name: container build
on:
  push:
    branches: [ main ]
jobs:
  earthly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Earthly
        uses: earthly/actions-setup@v1.0.11
        with:
          version: v0.7.8
      - name: Login to ghcr.io
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push docker image as latest
        env:
          CACHE_REGISTRY: ghcr.io/${{ github.repository_owner }}/satymathbot:cache
        run: |
          earthly --push --ci --remote-cache="${CACHE_REGISTRY}" +images --repo=ghcr.io/namachan10777
