name: CodeBuild
on:
  push:
    tags:
      - '*'
    branches-ignore:
      - '**'
jobs:
  codebuild:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::966924987919:role/SatymathBotGitHubActions
          aws-region: ap-northeast-1
      - name: Run CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: satymathbot
