name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: cargo-v1-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy
    - name: Install jsonnet
      uses: kobtea/setup-jsonnet-action@v1
    - name: Build
      run: cargo build --verbose
      working-directory: app
    - name: Test
      run: cargo test --verbose
      working-directory: app
    - name: Format
      run: cargo fmt -- --check
      working-directory: app
    - name: Clippy
      run: cargo clippy -- -D warnings
      working-directory: app

