name: Test

on: [push, pull_request]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Install golint
      run: go get golang.org/x/lint/golint

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Vet
      run: go vet ./...

    - name: Fmt
      run:
        go fmt -x ./... &&
        test -z $(go fmt ./...)

    - name: Lint
      run: golint -set_exit_status ./...

    - name: Hadolint
      run: |
          wget https://github.com/hadolint/hadolint/releases/download/v1.19.0/hadolint-Linux-x86_64 -O ./hadolint &&
          chmod +x ./hadolint &&
          ./hadolint dockerfile/prod/Dockerfile
