name: Test
on: [push, pull_request]
jobs:
  frontend:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [18]
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 7
      working-directory: web
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
      working-directory: web
    - name: Install
      run: pnpm install --frozen-lockfile
      working-directory: web
    - name: Check
      run: pnpm run check
      working-directory: web
    - name: Build test
      run: pnpm run build
      working-directory: web
  test:
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: cargo-v1-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy
    - name: Build
      run: cargo build --verbose
      working-directory: app
    - name: Test
      run: cargo test --verbose
      working-directory: app
    - name: Format
      run: cargo fmt -- --check
      working-directory: app
    - name: Clippy
      run: cargo clippy -- -D warnings
      working-directory: app

